### ISSUE TITLE
Composition associativity is broken?

### ISSUE THREAD

**Issue by klntsky** [safareli/purescript-stacksafe-function#5]
```purescript
addA :: Func String String
addA = Func (_ <> "a")

addB :: Func String String
addB = Func (_ <> "b")

addC :: Func String String
addC = Func (_ <> "c")

main :: Effect Unit
main = do
  assertEqual { expected: (run ((addA <<< addB) <<< addC) "")
              , actual: (run (addA <<< (addB <<< addC)) "") }
```

```
Error: Expected: "cba"
Actual:   "cab"
```

I'd like to note that [testAssociativity](https://github.com/safareli/purescript-stacksafe-function/blob/master/test/src/Main.purs#L40) is in fact testing associativity of integer addition, not associativity of `Func` composition.

Also, dependencies are outdated.

**Comment by safareli** [comment]
@8084 I have not used this lib at all, and I'm very curious about the usecase you have for it would be great if you can share it :d

**Comment by klntsky** [comment]
I wanted to use it to re-implement [dlist](http://hackage.haskell.org/package/dlist) in purescript.

I ended up [storing functions within array](https://github.com/8084/purescript-difference-containers/blob/master/src/Containers/Difference.purs#L33), which sort of defeats the purpose of using dlists in the first place, while also being less performant, but this can be fixed now.

**Comment by safareli** [comment]
Great!
